server:
  port: 8081

spring:
  application:
    name: service01

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://15.164.216.169:8761/eureka
